### PR TITLE
all human mouse alignments

### PR DESCRIPTION
**Pull request by samuelchen2004**
added around 28 alignments from human/mouse to other species

### CODE REVIEW

**Comment by lidaof** [comment]
Thank you @samuelchen2004 ! Can you work with @xzhuo to move the alignment track files to vizhub and update the urls after please?

thanks again!

**Comment by xzhuo** [comment]
All the new track files have been uploaded to vizhub now.

**Comment by lidaof** [comment]
Thank you @xzhuo

**Comment by xzhuo** [comment]
I am getting an error with "TypeError: Cannot read property 'publicHubList' of null" in app.js line 234. Any idea? @lidaof

**Comment by xzhuo** [comment]
have mm9-hg38 (missing alignment track file), mm10-cavPor3, mm10-rn5, hg38-rn5, hg19-rn5, hg19-cavPor3 alignments (missing query genomes) deleted. Now all of the tracks load with no error.

**Comment by xzhuo** [comment]
All tracks are working and it is ready to be merged.

**Pull request merged**
