### PR TITLE
correct RM strand if the whole region is reverse

### PR DESCRIPTION
**Pull request by xzhuo**
Reverse strand arrow if the whole alignment is placed reversely.

### CODE REVIEW

**Comment by lidaof** [comment]
Hi @xzhuo , is this supposed to work with GenomeAlign track?

**Comment by xzhuo** [comment]
yes. if the alignment track is reverse, then + in RM track goes from right to left, - in RM track goes from left to right.

**Comment by xzhuo** [comment]
RM track behaves the same without alignment track.

**Comment by xzhuo** [comment]
Added find mode alignment track hover box

**Comment by lidaof** [comment]
Hi Xiaoyu, can you also take screenshots please?

**Comment by xzhuo** [comment]
rough alignment segment highlight:
image

fine alignment hoover box:
image

**Comment by xzhuo** [comment]
another push the make the coordinates correct. I think this part is done now.

**Comment by xzhuo** [comment]
make each dash in gap matches a nucleotide:
image

**Comment by lidaof** [comment]
this is very neat!! thanks Xiaoyu! the white arrows do look a little bit distracting...

**Comment by xzhuo** [comment]
I placed arrows in between letters, is it better?
image

**Comment by lidaof** [comment]
much better! do we need arrows for primary genome?

**Comment by xzhuo** [comment]
I can... but the primary genome always goes right, is it necessary?

**Comment by lidaof** [comment]
yeap, i agree, i was trying to discuss. I am thinking adding arrows only for visualization aspect...kind of consistency.. we can discuss with Renee @EvoAlias

**Comment by EvoAlias** [comment]
I don't think its necessary, because the base genome is always in the forward direction.

**Comment by xzhuo** [comment]
I think this part is ready to be merged. I am beginning to work on the multiple-species alignment feature.

**Comment by lidaof** [comment]
Thank Xiaoyu @xzhuo . I will start to review code and merge shortly.

**Pull request merged**
