### PR TITLE
Alignment enhancement

### PR DESCRIPTION
**Pull request by xzhuo**
1. Add arrows illustrate alignment direction; 
2. Add short ticks for aligned bps; 
3. Render gap size between alignment placement; 
4. Always show alignment gaps in the primary sequence;
5. Show only one chromosome name in ruler track;
6. Remove vertical divider of features;
7. Remove boxes surrounding features and leave only a small vertical line at the edge of each feature.

### CODE REVIEW

**Comment by lidaof** [comment]
Good job @xzhuo , we will have to find a better way to toggle the VerticalDiveider component.

**Comment by xzhuo** [comment]
> Good job @xzhuo , we will have to find a better way to toggle the VerticalDiveider component.

I replaced the vertical divider with short, vertical lines in the ruler track. Btw, the old browser does not have the vertical dividers. I feel they are not necessary...

**Comment by lidaof** [comment]
vertical lines will be useful for region set view:

image

vs.

image

let's think about this and we can merge.

**Comment by xzhuo** [comment]
> vertical lines will be useful for region set view:
> 
> image
> 
> vs.
> 
> image
> 
> let's think about this and we can merge.

Add one divider between chromosomes?

**Comment by xzhuo** [comment]
> vertical lines will be useful for region set view:
> 
> image
> 
> vs.
> 
> image
> 
> let's think about this and we can merge.

Your commit looks good!

**Comment by lidaof** [comment]
Very nice display of gap text!! Thanks @xzhuo !

**Pull request merged**
